import { BaseModel, BaseModelType, MarketModel, ModelType } from "../types/model.types";

const CHECKPOINTS = [
  {
    url: "https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned.safetensors?download=true",
    filename: "SD1.5_pured.safetensors",
    path: "checkpoints",
    sha256: "1a189f0be69d6106a48548e7626207dddd7042a418dbf372cefd05e0cdba61b6",
    baseModel: BaseModel.SD15,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '7.7 GB',
    imageUrls: ["https://image.app-image.com/Models%2Fsd-1-5.png"],
    reference: "https://huggingface.co/runwayml/stable-diffusion-v1-5/blob/main/v1-5-pruned.safetensors"
  },
  {
    url: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0.safetensors?download=true",
    filename: "SDXL_v1_base.safetensors",
    path: "checkpoints",
    sha256: "31e35c80fc4829d14f90153f4c74cd59c90b779f6afe05a74cd6120b893f7e5b",
    baseModel: BaseModel.SDXL10,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '6.94 GB',
    imageUrls: ["https://image.app-image.com/Models%2Fsdxl-base.jpeg"],
    reference: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0"
  },
  {
    url: "https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0/resolve/main/sd_xl_refiner_1.0.safetensors?download=true",
    filename: "SDXL_v1_refiner.safetensors",
    path: "checkpoints",
    sha256: "7440042bbdc8a24813002c09b6b69b64dc90fded4472613437b7f55f9b7d9c5f",
    baseModel: BaseModel.SDXL10,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '6.08 GB',
    imageUrls: ["https://image.app-image.com/Models%2Fsdxl-refiner.jpeg"],
    reference: "https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0"
  },
  {
    url: "https://civitai.com/api/download/models/128713",
    filename: "dreamshaper_v8.safetensors",
    path: "checkpoints",
    sha256: "879DB523C30D3B9017143D56705015E15A2CB5628762C11D086FED9538ABD7FD",
    baseModel: BaseModel.SD15,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '1.99 GB',
    imageUrls: ["https://comflowy.com/model/dream-shaper/modelimg.png"],
    reference: "https://comflowy.com/model/dream-shaper-v-8"
  },
  {
    url: "https://civitai.com/api/download/models/131004?type=Model&format=SafeTensor&size=pruned&fp=fp16",
    filename: "dreamshaper_v8_Inpainting.safetensors",
    path: "checkpoints",
    sha256: "",
    baseModel: BaseModel.SD15,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '1.99 GB',
    imageUrls: ["https://comflowy.com/model/dream-shaper-inpainting/modelimg.png"],
    reference: "https://comflowy.com/model/dream-shaper-inpainting-v-8"
  },
  {
    url: "https://civitai.com/api/download/models/252914?type=Model&format=SafeTensor&size=pruned&fp=fp16",
    filename: "dreamshaper_v8_LCM.safetensors",
    path: "checkpoints",
    sha256: "",
    baseModel: BaseModel.SD15,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '1.99 GB',
    imageUrls: ["https://comflowy.com/model/dream-shaper-lcm/modelimg.png"],
    reference: "https://comflowy.com/model/dream-shaper-lcm"
  },
  {
    url: "https://civitai.com/api/download/models/351306?type=Model&format=SafeTensor&size=full&fp=fp16",
    filename: "dreamshaperXL_v21_TurboDPMSDE.safetensors",
    path: "checkpoints",
    sha256: "4496B36D48BFD7CFE4E5DBCE3485DB567BCEFA2BEF7238D290DBD45612125083",
    baseModel: BaseModel.SDXLTurbo,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '6.46 GB',
    imageUrls: ["https://www.comflowy.com/model/dream-shaper-xl/modelimg.png"],
    reference: "https://comflowy.com/model/dream-shaper-xl",
  },
  {
    url: "https://civitai.com/api/download/models/354657?type=Model&format=SafeTensor&size=full&fp=fp16",
    filename: "dreamshaperXL_LightningDPMSDE.safetensors",
    path: "checkpoints",
    sha256: "FDBE56354B8F876B736F24D3AD867ECD4140C019F57642EC8DDD878088D44F64",
    baseModel: BaseModel.SDXLLightning,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '6.46 GB',
    imageUrls: ["https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/ec16aedf-f847-45ff-a76c-81b1adb9f59c/width=450/31072648-3698264988-In%20Casey%20Baugh's%20evocative%20style,%20art%20of%20a%20beautiful%20young%20girl%20cyborg%20with%20long%20brown%20hair,%20futuristic,%20scifi,%20intricate,%20elega.jpeg"],
    reference: "https://civitai.com/models/112902?modelVersionId=354657",
  },
  {
    url: "https://civitai.com/api/download/models/348913?type=Model&format=SafeTensor&size=full&fp=fp16",
    filename: "juggernautXL_v9_RDPhoto2.safetensors",
    path: "checkpoints",
    sha256: "C9E3E68F89B8E38689E1097D4BE4573CF308DE4E3FD044C64CA697BDB4AA8BCA",
    baseModel: BaseModel.SDXL10,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '6.62 GB',
    imageUrls: ["https://comflowy.com/model/realistic/juggernaut-xl-modelimg.png"],
    reference: "https://comflowy.com/model/juggernaut-xl",
  },
  {
    url: "https://civitai.com/api/download/models/357609?type=Model&format=SafeTensor&size=full&fp=fp16",
    filename: "juggernautXL_v9_RDPhoto2_Lightning.safetensors",
    path: "checkpoints",
    sha256: "C8DF560D2992AC04299412BE6A36FA53A4E7A1B74F27B94867AD3F84F4B425A5",
    baseModel: BaseModel.SDXLLightning,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '6.62 GB',
    imageUrls: ["https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/37ad832d-92d6-4698-b24b-faada23fe314/width=450/00016-beautiful%20lady,%20(freckles),%20big%20smile,%20ruby%20eyes,%20short%20hair,%20dark%20makeup,%20hyperdetailed%20photography,%20soft%20light,%20head%20and%20shoul.jpeg"],
    reference: "https://comflowy.com/model/juggernaut-xl",
  },
  {
    url: "https://civitai.com/api/download/models/130072?type=Model&format=SafeTensor&size=full&fp=fp16",
    filename: "realisticVision_v51_VAE.safetensors",
    path: "checkpoints",
    sha256: "EF76AA2332635F4352463343BEEC9C5AAE3BD107A73C0FD7221ABBBCF8BD5470",
    baseModel: BaseModel.SD15,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '3.97 GB',
    imageUrls: ["https://comflowy.com/model/realistic/realistic-version-modelimg.png"],
    reference: "https://comflowy.com/model/realistic-vision-v-6",
  },
  {
    url: "https://civitai.com/api/download/models/130090?type=Model&format=PickleTensor&size=full&fp=fp16",
    filename: "realisticVision_v51_VAE_Inpaninting.safetensors",
    path: "checkpoints",
    sha256: "9AE8E9632C05FC45B6DA168AC4C25CDF6CA59BA3CD487B08974B5B2A54839629",
    baseModel: BaseModel.SD15,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '3.97 GB',
    imageUrls: ["https://comflowy.com/model/realistic/realistic-version-modelimg.png"],
    reference: "https://comflowy.com/model/realistic-vision-v-6",
  },
  {
    url: "https://civitai.com/api/download/models/176425?type=Model&format=SafeTensor&size=pruned&fp=fp16",
    filename: "majicMIXrealistic_v7.safetensors",
    path: "checkpoints",
    sha256: "7C819B6D13663ED720C2254F4FE18373107DFEF2448D337913C8FC545640881E",
    baseModel: BaseModel.SD15,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '1.99 GB',
    imageUrls: ["https://comflowy.com/model/realistic/majicMIX-realistic-modelimg.png"],
    reference: "https://comflowy.com/model/majicMIX-realistic",
  },
  {
    url: "https://civitai.com/api/download/models/221343?type=Model&format=SafeTensor&size=pruned&fp=fp16",
    filename: "majicMIXrealistic_v7_Inpainting.safetensors",
    path: "checkpoints",
    sha256: "B65F69645C4A02F66C163DAB7201EF92F61260C6A8031BC1A7D028A14D916034",
    baseModel: BaseModel.SD15,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '1.99 GB',
    imageUrls: ["https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/79b5f2e1-d055-4290-95b4-dadeb61c7a0e/width=450/00045-592090504-(green%20dress_1.2),1girl,_lora_hourglassv01_0.6_,hourglass%20body%20shape,waist%20up,.jpeg"],
    reference: "https://civitai.com/models/43331?modelVersionId=221343",
  },
  {
    url: "https://civitai.com/api/download/models/384264?type=Model&format=SafeTensor&size=full&fp=fp16",
    filename: "anythingXL.safetensors",
    path: "checkpoints",
    sha256: "8421598E930BE75D6E7AFC80DB0EF38CF324901966BD0FB8739E69C448E18A89",
    baseModel: BaseModel.SDXL10,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '6.46 GB',
    imageUrls: ["https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/4bdea703-131d-403c-89c7-d823ad8683a9/width=450/6846b1b9-8dca-7eee-9ab1-4617ae9fe8111.jpeg"],
    reference: "https://civitai.com/models/9409/or-anything-xl",
  },
  {
    url: "https://civitai.com/api/download/models/30163?type=Model&format=SafeTensor&size=full&fp=fp16",
    filename: "anything_v5.safetensors",
    path: "checkpoints",
    sha256: "7F96A1A9CA9B3A3242A9AE95D19284F0D2DA8D5282B42D2D974398BF7663A252",
    baseModel: BaseModel.SD15,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '1.99 GB',
    imageUrls: ["https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/331caf64-8b9f-4811-9c20-83d55e7c6ce8/width=450/QQ%E5%9B%BE%E7%89%8720230530091931.jpeg"],
    reference: "https://civitai.com/models/9409?modelVersionId=30163",
  },
  {
    url: "https://civitai.com/api/download/models/5581?type=Model&format=SafeTensor&size=full&fp=fp16",
    filename: "anythingelseV4_v45.safetensors",
    path: "checkpoints",
    sha256: "1D1E459F9F549A404746390DE21DF33B8C8134F863B3B5DA7D784843E782900A",
    baseModel: BaseModel.SD15,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '7.17 GB',
    imageUrls: ["https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/c128dda2-207b-4d6f-0d20-33bb8e3b6d00/width=450/example-2.png-00.jpeg"],
    reference: "https://civitai.com/models/4855/anythingelse-v4",
  },
  {
    url: "https://civitai.com/api/download/models/293564?type=Model&format=SafeTensor&size=full&fp=fp32",
    filename: "animagineXL_v3.safetensors",
    path: "checkpoints",
    sha256: "1449E5B0B9DE87B0F414C5F29CB11CE3B3DC61FA2B320E784C9441720BF7B766",
    baseModel: BaseModel.SDXL10,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '6.46 GB',
    imageUrls: ["https://comflowy.com/model/anime/animagine-xl-modelimg.png"],
    reference: "https://comflowy.com/model/animagine-xl",
  },
  {
    url: "https://civitai.com/api/download/models/119057?type=Model&format=SafeTensor&size=pruned&fp=fp16",
    filename: "meinaMix_v11.safetensors",
    path: "checkpoints",
    sha256: "54EF3E3610EEE7F0F6C9F9B82EEE26AA404598512D800494D1DB344E3BC560B1",
    baseModel: BaseModel.SD15,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '1.99 GB',
    imageUrls: ["https://comflowy.com/model/anime/meina-mix-modelimg.png"],
    reference: "https://comflowy.com/model/meina-mix",
  },
  {
    url: "https://civitai.com/api/download/models/120702?type=Model&format=SafeTensor&size=pruned&fp=fp16",
    filename: "meinaMix_v11_Inpainting.safetensors",
    path: "checkpoints",
    sha256: "E1D224FCA30B52B7B43438F8F03FF2BD57E9CB83854DE057CF691990B2481EDD",
    baseModel: BaseModel.SD15,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '1.99 GB',
    imageUrls: ["https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/5b8e2cde-3139-4563-acbf-465982377123/width=450/00079-122012064.jpeg"],
    reference: "https://comflowy.com/model/meina-mix",
  },
  {
    url: "https://civitai.com/api/download/models/428862?type=Model&format=SafeTensor&size=full&fp=fp32",
    filename: "reVAnimated_v2_VAE.safetensors",
    path: "checkpoints",
    sha256: "7611DD3F1CEB25819DDF386EF048B80B406EC74567E56DA687F2E4EA85358BDD",
    baseModel: BaseModel.SD15,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '5.28 GB',
    imageUrls: ["https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/21cc5933-6827-41ab-8267-fd0df248e75e/width=450/352539-735323568-2-revAnimated_V2_Rebirth.jpeg"],
    reference: "https://civitai.com/models/7371?modelVersionId=428862",
  },
  {
    url: "https://civitai.com/api/download/models/429454?type=Model&format=SafeTensor&size=pruned&fp=fp16",
    filename: "epiCPhotoGasm_UltimateFidelity.safetensors",
    path: "checkpoints",
    sha256: "E44C7B30C64FF0D7BAFB68ED94D0B2F5CF864C23D4C5095731F73239FC636F55",
    baseModel: BaseModel.SD15,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '1.99 GB',
    imageUrls: ["https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/58e93980-ae46-45bc-ba69-67c7c2f18646/width=450/00684-1152893015.jpeg"],
    reference: "https://civitai.com/models/132632/epicphotogasm",
  },
  {
    url: "https://civitai.com/api/download/models/134084?type=Model&format=SafeTensor&size=full&fp=fp32",
    filename: "absolutereality_v181_Inpainting.safetensors",
    path: "checkpoints",
    sha256: "7E16C94105E0B72C0124A02D542E83937E38A0B96BB566F0BFA04D2EF17D0502",
    baseModel: BaseModel.SD15,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '3.97 GB',
    imageUrls: ["https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/93d5336b-6e5a-4c87-ad03-7805f0964549/width=450/00995-1650465319-cgmech,%20beautiful%20eyes,%20upper%20body,%20underboob,%20portrait,%20robot,white%20orange%20armor,%20shimmering%20blue%20hair,%20neon%20light,%208K,%20RAW,%20be.jpeg"],
    reference: "https://civitai.com/models/81458/absolutereality",
  },
  {
    url: "https://civitai.com/api/download/models/132760?type=Model&format=SafeTensor&size=pruned&fp=fp16",
    filename: "absolutereality_v181.safetensors",
    path: "checkpoints",
    sha256: "463D6A9FE8A4B56A4D69EF3692074C0617428DFD8E8F12F9EFE3B1E9A71717CE",
    baseModel: BaseModel.SD15,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '1.99 GB',
    imageUrls: ["https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/0375afda-d837-4cf9-a0f1-958810ab300d/width=450/26072207-5775662-(masterpiece),%20(extremely%20intricate_1.3),,%20(realistic),%20portrait%20of%20a%20girl,%20the%20most%20beautiful%20in%20the%20world,%20(medieval%20armor),%20m.jpeg"],
    reference: "https://civitai.com/models/81458/absolutereality",
  },
  {
    url: "https://civitai.com/api/download/models/302809?type=Model&format=SafeTensor&size=pruned&fp=fp16",
    filename: "photonium_v1.safetensors",
    path: "checkpoints",
    sha256: "8875F635909C37EE57741C556906B1C83D32F1B2D2F792812F9E89C3D3C0B466",
    baseModel: BaseModel.SDXL10,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '6.46 GB',
    imageUrls: ["https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/796869a1-ae04-4b67-bb3d-4bffe6c9d566/width=450/image_00001_.jpeg"],
    reference: "https://civitai.com/models/268578/photonium",
  },
  {
    url: "https://civitai.com/api/download/models/143906?type=Model&format=SafeTensor&size=pruned&fp=fp16",
    filename: "epiCRealism_NaturalSinRC1_VAE.safetensors",
    path: "checkpoints",
    sha256: "84D76A0328EE5A1A2A1D466BA7478AB59183E3FEA385441528AA4C5D567FD43E",
    baseModel: BaseModel.SD15,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '1.99 GB',
    imageUrls: ["https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/3822f91b-5f4e-4df6-8934-2a453f13b40e/width=450/02499-144278541.jpeg"],
    reference: "https://civitai.com/models/25694/epicrealism",
  },
  {
    url: "https://civitai.com/api/download/models/329420?type=Model&format=SafeTensor&size=pruned&fp=fp16",
    filename: "albedobaseXL_v21.safetensors",
    path: "checkpoints",
    sha256: "1718B5BB2DA1EF4815FEE8AF8A7FC2FA8AB8F467B279EDED4D991EA0CCE59A6D",
    baseModel: BaseModel.SDXL10,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '6.46 GB',
    imageUrls: ["https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/af1f30e8-1eff-4322-ac24-8a1b83959628/width=450/0.jpeg"],
    reference: "https://civitai.com/models/140737/albedobase-xl",
  },
  {
    url: "https://huggingface.co/playgroundai/playground-v2.5-1024px-aesthetic/resolve/main/playground-v2.5-1024px-aesthetic.fp16.safetensors?download=true",
    filename: "playground_v2.5_1024px_aesthetic.safetensors",
    path: "checkpoints",
    sha256: "956dca99114aaa5c3eb526381309d37ee96737e78ed64c8ae613409f47c3f65a",
    baseModel: BaseModel.PlaygroundV2,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '13.9 GB',
    imageUrls: ["https://image.app-image.com/Models%2Fplayground.jpeg"],
    reference: "https://huggingface.co/playgroundai/playground-v2.5-1024px-aesthetic",
  },
  {
    url: "https://civitai.com/api/download/models/445348?type=Model&format=SafeTensor&size=pruned&fp=fp16",
    filename: "copaxTimeLessXL_v12.safetensors",
    path: "checkpoints",
    sha256: "2E1C9E1B1685ABEF65D1E3D0C8931A6C567BB17FA556785D2971007973F20B8D",
    baseModel: BaseModel.SDXL10,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '6.46 GB',
    imageUrls: ["https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/3bb3c613-f56c-486b-927e-cc20721db750/width=450/00221-2229083410.jpeg"],
    reference: "https://civitai.com/models/118111/copax-timelessxl-sdxl10",
  },
  {
    url: "https://civitai.com/api/download/models/404559?type=Model&format=SafeTensor&size=pruned&fp=fp16",
    filename: "copaxTimeLessXL_v11_lightning.safetensors",
    path: "checkpoints",
    sha256: "58ED423904C411AB00078FBE7E47003F61D16EB20820D7699D8EF02C535C57F8",
    baseModel: BaseModel.SDXLLightning,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '6.46 GB',
    imageUrls: ["https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/66d4a79a-5da7-48c9-9a29-bcf6fcdbaf55/width=450/00044-1262508703.jpeg"],
    reference: "https://civitai.com/models/118111?modelVersionId=404559",
  },
  {
    url: "https://huggingface.co/TencentARC/MotionCtrl/resolve/main/motionctrl.pth?download=true",
    filename: "motionctrl.pth",
    path: "checkpoints",
    sha256: "efe225096946c804841c2a78c3624d77cade3ac021a2519a2f0f85708a0fe46c",
    baseModel: BaseModel.OTHER,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '4.02 GB',
    imageUrls: ["https://raw.githubusercontent.com/TencentARC/MotionCtrl/main/assets/svd/00_ibzz5-dxv2h.gif"],
    reference: "https://huggingface.co/TencentARC/MotionCtrl",
  },
  {
    url: "https://huggingface.co/TencentARC/MotionCtrl/resolve/main/motionctrl_svd.ckpt?download=true",
    filename: "motionctrl_svd.ckpt",
    path: "checkpoints",
    sha256: "979e36a5e0b8efd75fa23fbf4b209cd3b14b4a8fa6de53d4121f3559dc839f3b",
    baseModel: BaseModel.OTHER,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '9.61 GB',
    imageUrls: ["https://raw.githubusercontent.com/TencentARC/MotionCtrl/main/assets/svd/00_ibzz5-dxv2h.gif"],
    reference: "https://huggingface.co/TencentARC/MotionCtrl",
  },
  {
    url: "https://civitai.com/api/download/models/329995",
    filename: "svd_xt_v11.safetensors",
    path: "checkpoints",
    sha256: "69ccfea1bb45dd63b3ba8b6cfe8b0d45d780995dfdde590aeaa97cc567018d33",
    baseModel: BaseModel.SVDXT,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '4.78 GB',
    imageUrls: ["https://image.app-image.com/Models%2Fsvd-xt.jpeg"],
    reference: "https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt-1-1/blob/main/svd11.webp",
  },
  {
    url: "https://huggingface.co/stabilityai/stable-video-diffusion-img2vid/resolve/main/svd.safetensors?download=true",
    filename: "svd.safetensors",
    path: "checkpoints",
    sha256: "3e0994626df395a3831de024f11b2d9d241143bb6f16e2efbacced248aa18ce0",
    baseModel: BaseModel.SVD,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '9.56 GB',
    imageUrls: ["https://image.app-image.com/Models%2Fsvd.jpeg"],
    reference: "https://huggingface.co/stabilityai/stable-video-diffusion-img2vid",
  },
  {
    url: "https://huggingface.co/stabilityai/stable-cascade/resolve/main/comfyui_checkpoints/stable_cascade_stage_b.safetensors?download=true",
    filename: "stable_cascade_stage_b.safetensors",
    path: "checkpoints",
    sha256: "7b431ea7d0f10e72b3eaece353bf6bf2f6bc717b6f4207411be186b40dec1f43",
    baseModel: BaseModel.StableCascade,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '6.25 GB',
    imageUrls: ["https://image.app-image.com/Models%2Fsc.jpeg"],
    reference: "https://huggingface.co/stabilityai/stable-cascade",
  },
  {
    url: "https://huggingface.co/stabilityai/stable-cascade/resolve/main/comfyui_checkpoints/stable_cascade_stage_c.safetensors?download=true",
    filename: "stable_cascade_stage_c.safetensors",
    path: "checkpoints",
    sha256: "39cec96c7212607f9e526db719bf1df507166d09f4748676c13b0d31cd4adb07",
    baseModel: BaseModel.StableCascade,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '14.4 GB',
    imageUrls: ["https://image.app-image.com/Models%2Fsc.jpeg"],
    reference: "https://huggingface.co/stabilityai/stable-cascade",
  },
  {
    url: "https://huggingface.co/ByteDance/SDXL-Lightning/resolve/main/sdxl_lightning_1step_x0.safetensors?download=true",
    filename: "sdxl_lightning_1step_x0.safetensors",
    path: "checkpoints",
    sha256: "dd8d4c2b341cdbbe88178135786bd4ea1a6f46d6dcb719f05524a5e761ae19a0",
    baseModel: BaseModel.SDXLLightning,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '6.94 GB',
    imageUrls: ["https://image.app-image.com/Models%2Fsdxl-lightning.jpeg"],
    reference: "https://huggingface.co/ByteDance/SDXL-Lightning",
  },
  {
    url: "https://huggingface.co/ByteDance/SDXL-Lightning/resolve/main/sdxl_lightning_2step.safetensors?download=true",
    filename: "sdxl_lightning_2step.safetensors",
    path: "checkpoints",
    sha256: "87e61f60b85d9f1c577bd9053872c7678b7d39f6f52d470081ff6ea3b49ddf98",
    baseModel: BaseModel.SDXLLightning,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '6.94 GB',
    imageUrls: ["https://image.app-image.com/Models%2Fsdxl-lightning.jpeg"],
    reference: "https://huggingface.co/ByteDance/SDXL-Lightning",
  },
  {
    url: "https://huggingface.co/ByteDance/SDXL-Lightning/resolve/main/sdxl_lightning_4step.safetensors?download=true",
    filename: "sdxl_lightning_4step.safetensors",
    path: "checkpoints",
    sha256: "e0d996ee0013e79d9d3561f50fcafb9a17e3ff07b780358e3b66d67932c4d490",
    baseModel: BaseModel.SDXLLightning,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '6.94 GB',
    imageUrls: ["https://image.app-image.com/Models%2Fsdxl-lightning.jpeg"],
    reference: "https://huggingface.co/ByteDance/SDXL-Lightning",
  },
  {
    url: "https://huggingface.co/ByteDance/SDXL-Lightning/resolve/main/sdxl_lightning_8step.safetensors?download=true",
    filename: "sdxl_lightning_8step.safetensors",
    path: "checkpoints",
    sha256: "43f0501ac4ffcef84f3fc32a47779f24c181647fa97ef7f5ec4428107d732ae9",
    baseModel: BaseModel.SDXLLightning,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '6.94 GB',
    imageUrls: ["https://image.app-image.com/Models%2Fsdxl-lightning.jpeg"],
    reference: "https://huggingface.co/ByteDance/SDXL-Lightning",
  },
  {
    url: "https://civitai.com/api/download/models/490254?type=Model&format=SafeTensor&size=full&fp=fp16",
    filename: "ZavyChromaXL_v7.safetensors",
    path: "checkpoints",
    sha256: "3E0A3274D0B0EB83BA3F32BA6A37F40F903736F56B29DB3EC1D0DE66FE22070A",
    baseModel: BaseModel.SDXL10,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '6.62 GB',
    imageUrls: ["https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/ef791b34-d135-48a5-821e-0b1647897221/width=450/20-51-55_940838993318669.jpeg"],
    reference: "https://civitai.com/models/119229/zavychromaxl",
  },
  {
    url: "https://civitai.com/api/download/models/355900?type=Model&format=SafeTensor&size=full&fp=fp16",
    filename: "Proteus_v4.safetensors",
    path: "checkpoints",
    sha256: "F5A35025A254B2223A8AE1051354696A2875FBFE3EA92EFC23E1F6497A2A476E",
    baseModel: BaseModel.SDXL10,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '6.46 GB',
    imageUrls: ["https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/64bedb59-0776-4add-ad53-0ba47efb8e6f/width=450/upscaled_image2.jpeg"],
    reference: "https://civitai.com/models/267242/proteus",
  },
  {
    url: "https://huggingface.co/stabilityai/stable-diffusion-2-1-unclip/resolve/main/sd21-unclip-h.ckpt?download=true",
    filename: "sd21-unclip-h.ckpt",
    path: "checkpoints", 
    sha256: "4124cbcf397ace8c536908f5f877a1f091a41168d1d3d9fd0c84484c1653693b",
    baseModel: BaseModel.OTHER,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '7.97 GB',
    imageUrls: ["https://image.app-image.com/Models%2Fsd-1-unclip.jpeg"],
    reference: "https://huggingface.co/stabilityai/stable-diffusion-2-1-unclip",
  },
  {
    url: "https://huggingface.co/stabilityai/stable-diffusion-2-1-unclip/resolve/main/sd21-unclip-l.ckpt?download=true",
    filename: "sd21-unclip-l.ckpt",
    path: "checkpoints",
    sha256: "ed12098385701c1850defd3d2bc20905c7c64dad3ccad895a7f13b406aab7602",
    baseModel: BaseModel.OTHER,
    type: ModelType.Checkpoint,
    description: "xxx",
    sizeGb: '6.16 GB',
    imageUrls: ["https://image.app-image.com/Models%2Fsd-1-unclip.jpeg"],
    reference: "https://huggingface.co/stabilityai/stable-diffusion-2-1-unclip",
  },
];

function findDuplicates(arr: { url: string; filename: string; path: string }[]) {
  const count: { [key: string]: number } = {};

  // 计算每个 filename 出现的次数
  for (const item of arr) {
    if (item.filename in count) {
      count[item.filename]++;
    } else {
      count[item.filename] = 1;
    }
  }

  // 过滤出出现次数大于 1 的元素
  const duplicates = arr.filter(item => count[item.filename] > 1);

  return duplicates;
}

// const duplicates = findDuplicates(CHECKPOINTS);
// console.log("duplicates", duplicates);

const LORAS = [
  {
    url: "https://civitai.com/api/download/models/28907?type=Model&format=SafeTensor&size=full&fp=fp16",
    filename: "animeoutlineV4_16.safetensors",
    path: "loras",
    sha256: "2FCD88E6AA07B2DB73BEFCA54B3956131E1DECC8E6E719508CE32C28768F9B91",
    baseModel: BaseModel.SD15,
    type: ModelType.LoRA,
    description: "xxx",
    sizeGb: '18.11 MB',
    imageUrls: ["https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/fab28432-7d00-43c4-fbd6-ac5989ebf000/width=450/326152.jpeg"],
    reference: "https://civitai.com/models/16014/anime-lineart-manga-like-style",
  },
  {
    url: "https://civitai.com/api/download/models/87153?type=Model&format=SafeTensor",
    filename: "addMoreDetails.safetensors",
    path: "loras",
    sha256: "D9CF2F88DEC53A8DD8C09ABA2B1D67963B265EBDF8255660F5BCD7F1C8EDBA33",
    baseModel: BaseModel.SD15,
    type: ModelType.LoRA,
    description: "xxx",
    sizeGb: '9.11 MB',
    imageUrls: ["https://comflowy.com/model/lora/add-more-details-modelimg.png"],
    reference: "https://comflowy.com/model/add-more-details",
  },
  {
    url: "https://civitai.com/api/download/models/196413?type=Model&format=SafeTensor",
    filename: "memoji.safetensors",
    path: "loras",
    sha256: "EA8C050A6DFF41D739C36B6FFB2091762340A8660310916720B6A9DD73C248C9",
    baseModel: BaseModel.SDXL10,
    type: ModelType.LoRA,
    description: "xxx",
    sizeGb: '217.96 MB',
    imageUrls: ["https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/151cfab6-0ebe-4bff-957b-3db7f354f13c/width=450/00007-3002880354.jpeg"],
    reference: "https://civitai.com/models/174943/memoji",
  },
  {
    url: "https://civitai.com/api/download/models/62833?type=Model&format=SafeTensor",
    filename: "addDetail.safetensors",
    path: "loras",
    sha256: "47AAAF0D2945CA937151D61304946DD229B3F072140B85484BC93E38F2A6E2F7",
    baseModel: BaseModel.SD15,
    type: ModelType.LoRA,
    description: "xxx",
    sizeGb: '36.11 MB',
    imageUrls: ["https://comflowy.com/model/lora/detail-tweaker-modelimg.png"],
    reference: "https://comflowy.com/model/detail-tweaker",
  },
  {
    url: "https://civitai.com/api/download/models/160130?type=Model&format=SafeTensor",
    filename: "StickersRedmond.safetensors",
    path: "loras",
    sha256: "927A840722D1AC9103223C09DA55CC3AE750300E1C0E22A15FFCF460AC6F8A56",
    baseModel: BaseModel.SDXL10,
    type: ModelType.LoRA,
    description: "xxx",
    sizeGb: '162.64 MB',
    imageUrls: ["https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/431c9ce7-bfbe-425b-9105-d0cb7539d8b0/width=450/00000-3383490575.jpeg"],
    reference: "https://civitai.com/models/144142/stickersredmond-stickers-lora-for-sd-xl",
  },
  {
    url: "https://civitai.com/api/download/models/221390?type=Model&format=SafeTensor",
    filename: "StudioGhibli.Redmond-StdGBRRedmAF-StudioGhibli.safetensors",
    path: "loras",
    sha256: "516FE22303B8A24F800A0A24A8F4C864121411B7261206C406183C1103B7BF37",
    baseModel: BaseModel.SDXL10,
    type: ModelType.LoRA,
    description: "xxx",
    sizeGb: '217.87 MB',
    imageUrls: ["https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/81ba5f5e-bf93-4ce1-b500-18eb6899e92c/width=450/00224-3646141139.jpeg"],
    reference: "https://civitai.com/models/137562/studioghibliredmond-studio-ghibli-lora-for-sd-xl",
  },
  {
    url: "https://civitai.com/api/download/models/236248?type=Model&format=SafeTensor",
    filename: "CLAYMATE_V2.03_.safetensors",
    path: "loras",
    sha256: "FC1790DDEC807108BB4125748C37B5B33C23806F2B5F74D1C5B8B19BF68B2284",
    baseModel: BaseModel.SDXL10,
    type: ModelType.LoRA,
    description: "xxx",
    sizeGb: '870.29 MB',
    imageUrls: ["https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/16bc2b66-0e0f-4ad3-aad4-8846720aad32/width=450/03370-3608067367-claymation,%20The%20Truman%20Show%20-%20A%20man%20discovers%20his%20entire%20life%20has%20been%20a%20reality%20TV%20show.%20_lora_CLAYMATE_V2.03__1_.jpeg"],
    reference: "https://civitai.com/models/208168/claymate-claymation-style-for-sdxl",
  },
  {
    url: "https://civitai.com/api/download/models/107366?type=Model&format=SafeTensor",
    filename: "3DMM_V12.safetensors",
    path: "loras",
    sha256: "8A419D0AA649BF496A6182E34C67FCF45E85ADEEADD26831D5537409F10DB88A",
    baseModel: BaseModel.SD15,
    type: ModelType.LoRA,
    description: "xxx",
    sizeGb: '36.11 MB',
    imageUrls: ["https://comflowy.com/model/lora/3d-rendering-style-modelimg.png"],
    reference: "https://comflowy.com/model/3d-rendering-style",
  },
  {
    url: "https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid_sd15_lora.safetensors?download=true",
    filename: "ip-adapter-faceid_sd15_lora.safetensors",
    path: "loras",
    sha256: "70699f0dbfadd47de1f81d263cf4c86bd4b7271d841304af9b340b3a7f38e86a",
    baseModel: BaseModel.SD15,
    type: ModelType.LoRA,
    description: "xxx",
    sizeGb: '51.1 MB',
    imageUrls: ["https://image.app-image.com/Models%2Fipadapter-faceid.png"],
    reference: "https://huggingface.co/h94/IP-Adapter-FaceID",
  },
  {
    url: "https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid_sdxl_lora.safetensors?download=true",
    filename: "ip-adapter-faceid_sdxl_lora.safetensors",
    path: "loras",
    sha256: "4fcf93d6e8dc8dd18f5f9e51c8306f369486ed0aa0780ade9961308aff7f0d64",
    baseModel: BaseModel.SDXL10,
    type: ModelType.LoRA,
    description: "xxx",
    sizeGb: '372 MB',
    imageUrls: ["https://image.app-image.com/Models%2Fipadapter-faceid-xl.jpeg"],
    reference: "https://huggingface.co/h94/IP-Adapter-FaceID",
  },
  {
    url: "https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid-plusv2_sd15_lora.safetensors?download=true",
    filename: "ip-adapter-faceid-plusv2_sd15_lora.safetensors",
    path: "loras",
    sha256: "8abff87a15a049f3e0186c2e82c1c8e77783baf2cfb63f34c412656052eb57b0",
    baseModel: BaseModel.SD15,
    type: ModelType.LoRA,
    description: "xxx",
    sizeGb: '51.1 MB',
    imageUrls: ["https://image.app-image.com/Models%2Fipadapter-faceid.png"],
    reference: "https://huggingface.co/h94/IP-Adapter-FaceID",
  },
  {
    url: "https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid-plusv2_sdxl_lora.safetensors?download=true",
    filename: "ip-adapter-faceid-plusv2_sdxl_lora.safetensors",
    path: "loras",
    sha256: "f24b4bb2dad6638a09c00f151cde84991baf374409385bcbab53c1871a30cb7b",
    baseModel: BaseModel.SDXL10,
    type: ModelType.LoRA,
    description: "xxx",
    sizeGb: '372 MB',
    imageUrls: ["https://image.app-image.com/Models%2Fipadapter-faceid-xl.jpeg"],
    reference: "https://huggingface.co/h94/IP-Adapter-FaceID",
  },
  {
    url: "https://huggingface.co/latent-consistency/lcm-lora-sdxl/resolve/main/pytorch_lora_weights.safetensors?download=true",
    filename: "lcm_lora_sdxl.safetensors",
    path: "loras",
    sha256: "a764e6859b6e04047cd761c08ff0cee96413a8e004c9f07707530cd776b19141",
    baseModel: BaseModel.SDXL10,
    type: ModelType.LoRA,
    description: "xxx",
    sizeGb: '394 MB',
    imageUrls: ["https://image.app-image.com/Models%2Flcm_sdx_lora_mix.png"],
    reference: "https://huggingface.co/latent-consistency/lcm-lora-sdxl",
  },
  {
    url: "https://huggingface.co/latent-consistency/lcm-lora-sdv1-5/resolve/main/pytorch_lora_weights.safetensors?download=true",
    filename: "lcm-lora-sd15.safetensors",
    path: "loras",
    sha256: "8f90d840e075ff588a58e22c6586e2ae9a6f7922996ee6649a7f01072333afe4",
    baseModel: BaseModel.SD15,
    type: ModelType.LoRA,
    description: "xxx",
    sizeGb: '135 MB',
    imageUrls: ["https://image.app-image.com/Models%2Flcm-lora-sdv1-5.png"],
    reference: "https://huggingface.co/latent-consistency/lcm-lora-sdxl",
  },
  {
    url: "https://huggingface.co/ByteDance/SDXL-Lightning/resolve/main/sdxl_lightning_2step_lora.safetensors?download=true",
    filename: "sdxl_lightning_2step_lora.safetensors",
    path: "loras",
    sha256: "04fafc778385b24144498a8247498ae4fb7a69f702ea0566bdce2845a31fcc43",
    baseModel: BaseModel.SDXL10,
    type: ModelType.LoRA,
    description: "xxx",
    sizeGb: '394 MB',
    imageUrls: ["https://image.app-image.com/Models%2Fsdxl-lightning-lora.jpeg"],
    reference: "https://huggingface.co/ByteDance/SDXL-Lightning",
  },
  {
    url: "https://huggingface.co/ByteDance/SDXL-Lightning/resolve/main/sdxl_lightning_4step_lora.safetensors?download=true",
    filename: "sdxl_lightning_4step_lora.safetensors",
    path: "loras",
    sha256: "bf56cf2657efb15e465d81402ed481d1e11c4677e4bcce1bc11fe71ad8506b79",
    baseModel: BaseModel.SDXL10,
    type: ModelType.LoRA,
    description: "xxx",
    sizeGb: '394 MB',
    imageUrls: ["https://image.app-image.com/Models%2Fsdxl-lightning-lora.jpeg"],
    reference: "https://huggingface.co/ByteDance/SDXL-Lightning",
  },
  {
    url: "https://huggingface.co/ByteDance/SDXL-Lightning/resolve/main/sdxl_lightning_8step_lora.safetensors?download=true",
    filename: "sdxl_lightning_8step_lora.safetensors",
    path: "loras",
    sha256: "5aa30d94cdf7950a8b53a693682650ee061eddb128c5435a8f88defea73b2ac6",
    baseModel: BaseModel.SDXL10,
    type: ModelType.LoRA,
    description: "xxx",
    sizeGb: '304 MB',
    imageUrls: ["https://image.app-image.com/Models%2Fsdxl-lightning-lora.jpeg"],
    reference: "https://huggingface.co/ByteDance/SDXL-Lightning",
  },
  {
    url: "https://huggingface.co/segmind/Segmind-VegaRT/resolve/main/pytorch_lora_weights.safetensors?download=true",
    filename: "segmindVegaRT.safetensors",
    path: "loras",
    sha256: "9b6e8cd833fa205eaeeed391ca623a6f2546e447470bd1c5dcce3fa8d2f26afb",
    baseModel: BaseModel.OTHER,
    type: ModelType.LoRA,
    description: "xxx",
    sizeGb: '239 MB',
    imageUrls: ["https://image.app-image.com/Models%2FsegmindVegaRT.jpeg"],
    reference: "https://huggingface.co/segmind/Segmind-VegaRT",
  },
];

const CONTROLNETS = [
  {
    url: "https://huggingface.co/stabilityai/control-lora/resolve/main/control-LoRAs-rank128/control-lora-canny-rank128.safetensors?download=true",
    filename: "control-lora-canny-rank128.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/stabilityai/control-lora/resolve/main/control-LoRAs-rank128/control-lora-depth-rank128.safetensors?download=true",
    filename: "control-lora-depth-rank128.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/stabilityai/control-lora/resolve/main/control-LoRAs-rank128/control-lora-recolor-rank128.safetensors?download=true",
    filename: "control-lora-recolor-rank128.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/stabilityai/control-lora/resolve/main/control-LoRAs-rank128/control-lora-sketch-rank128-metadata.safetensors?download=true",
    filename: "control-lora-sketch-rank128-metadata.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/stabilityai/control-lora/resolve/main/control-LoRAs-rank256/control-lora-canny-rank256.safetensors",
    filename: "control-lora-canny-rank256.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/stabilityai/control-lora/resolve/main/control-LoRAs-rank256/control-lora-depth-rank256.safetensors?download=true",
    filename: "control-lora-depth-rank256.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/stabilityai/control-lora/resolve/main/control-LoRAs-rank256/control-lora-recolor-rank256.safetensors?download=true",
    filename: "control-lora-recolor-rank256.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/stabilityai/control-lora/resolve/main/control-LoRAs-rank256/control-lora-sketch-rank256.safetensors?download=true",
    filename: "control-lora-sketch-rank256.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11e_sd15_ip2p.pth?download=true",
    filename: "control_v11e_sd15_ip2p.pth",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11e_sd15_shuffle.pth?download=true",
    filename: "control_v11e_sd15_shuffle.pth",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11f1e_sd15_tile.pth?download=true",
    filename: "control_v11f1e_sd15_tile.pth",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11f1p_sd15_depth.pth?download=true",
    filename: "control_v11f1p_sd15_depth.pth",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11p_sd15_canny.pth?download=true",
    filename: "control_v11p_sd15_canny.pth",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11p_sd15_inpaint.pth?download=true",
    filename: "control_v11p_sd15_inpaint.pth",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11p_sd15_lineart.pth?download=true",
    filename: "control_v11p_sd15_lineart.pth",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11p_sd15_mlsd.pth?download=true",
    filename: "control_v11p_sd15_mlsd.pth",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11p_sd15_normalbae.pth?download=true",
    filename: "control_v11p_sd15_normalbae.pth",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11p_sd15_openpose.pth?download=true",
    filename: "control_v11p_sd15_openpose.pth",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11p_sd15_scribble.pth?download=true",
    filename: "control_v11p_sd15_scribble.pth",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11p_sd15_seg.pth?download=true",
    filename: "control_v11p_sd15_seg.pth",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11p_sd15_softedge.pth?download=true",
    filename: "control_v11p_sd15_softedge.pth",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11p_sd15s2_lineart_anime.pth?download=true",
    filename: "control_v11p_sd15s2_lineart_anime.pth",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/diffusers_xl_canny_full.safetensors?download=true",
    filename: "diffusers_xl_canny_full.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/diffusers_xl_canny_mid.safetensors?download=true",
    filename: "diffusers_xl_canny_mid.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/diffusers_xl_canny_small.safetensors?download=true",
    filename: "diffusers_xl_canny_small.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/diffusers_xl_depth_full.safetensors?download=true",
    filename: "diffusers_xl_depth_full.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/diffusers_xl_depth_mid.safetensors?download=true",
    filename: "diffusers_xl_depth_mid.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/diffusers_xl_depth_small.safetensors?download=true",
    filename: "diffusers_xl_depth_small.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/ioclab_sd15_recolor.safetensors?download=true",
    filename: "ioclab_sd15_recolor.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/ip-adapter_sd15.pth?download=true",
    filename: "ip-adapter_sd15.pth",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/ip-adapter_sd15_plus.pth?download=true",
    filename: "ip-adapter_sd15_plus.pth",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/ip-adapter_xl.pth?download=true",
    filename: "ip-adapter_xl.pth",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/kohya_controllllite_xl_blur.safetensors?download=true",
    filename: "kohya_controllllite_xl_blur.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/kohya_controllllite_xl_blur_anime.safetensors?download=true",
    filename: "kohya_controllllite_xl_blur_anime.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/kohya_controllllite_xl_blur_anime_beta.safetensors?download=true",
    filename: "kohya_controllllite_xl_blur_anime_beta.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/kohya_controllllite_xl_canny.safetensors?download=true",
    filename: "kohya_controllllite_xl_canny.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/kohya_controllllite_xl_canny_anime.safetensors?download=true",
    filename: "kohya_controllllite_xl_canny_anime.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/kohya_controllllite_xl_depth.safetensors?download=true",
    filename: "kohya_controllllite_xl_depth.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/kohya_controllllite_xl_depth_anime.safetensors?download=true",
    filename: "kohya_controllllite_xl_depth_anime.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/kohya_controllllite_xl_openpose_anime.safetensors?download=true",
    filename: "kohya_controllllite_xl_openpose_anime.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/kohya_controllllite_xl_openpose_anime_v2.safetensors?download=true",
    filename: "kohya_controllllite_xl_openpose_anime_v2.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/kohya_controllllite_xl_scribble_anime.safetensors?download=true",
    filename: "kohya_controllllite_xl_scribble_anime.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/TheMistoAI/MistoLine/resolve/main/mistoLine_rank256.safetensors?download=true",
    filename: "mistoLine_rank256.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/TheMistoAI/MistoLine/resolve/main/mistoLine_fp16.safetensors?download=true",
    filename: "mistoLine_fp16.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/TTPlanet/TTPLanet_SDXL_Controlnet_Tile_Realistic/resolve/main/TTPLANET_Controlnet_Tile_realistic_v2_fp16.safetensors?download=true",
    filename: "TTPLANET_Controlnet_Tile_realistic_v2_fp16.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/sai_xl_canny_128lora.safetensors?download=true",
    filename: "sai_xl_canny_128lora.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/sai_xl_canny_256lora.safetensors?download=true",
    filename: "sai_xl_canny_256lora.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/sai_xl_depth_128lora.safetensors?download=true",
    filename: "sai_xl_depth_128lora.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/sai_xl_depth_256lora.safetensors?download=true",
    filename: "sai_xl_depth_256lora.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/sai_xl_recolor_128lora.safetensors?download=true",
    filename: "sai_xl_recolor_128lora.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/sai_xl_recolor_256lora.safetensors?download=true",
    filename: "sai_xl_recolor_256lora.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/sai_xl_sketch_128lora.safetensors?download=true",
    filename: "sai_xl_sketch_128lora.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/sai_xl_sketch_256lora.safetensors?download=true",
    filename: "sai_xl_sketch_256lora.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/sargezt_xl_depth.safetensors?download=true",
    filename: "sargezt_xl_depth.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/sargezt_xl_depth_faid_vidit.safetensors?download=true",
    filename: "sargezt_xl_depth_faid_vidit.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/sargezt_xl_depth_zeed.safetensors?download=true",
    filename: "sargezt_xl_depth_zeed.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/sargezt_xl_softedge.safetensors?download=true",
    filename: "sargezt_xl_softedge.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/t2i-adapter_diffusers_xl_canny.safetensors?download=true",
    filename: "t2i-adapter_diffusers_xl_canny.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/t2i-adapter_diffusers_xl_depth_midas.safetensors?download=true",
    filename: "t2i-adapter_diffusers_xl_depth_midas.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/t2i-adapter_diffusers_xl_lineart.safetensors?download=true",
    filename: "t2i-adapter_diffusers_xl_lineart.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/t2i-adapter_diffusers_xl_depth_zoe.safetensors?download=true",
    filename: "t2i-adapter_diffusers_xl_depth_zoe.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/t2i-adapter_diffusers_xl_openpose.safetensors?download=true",
    filename: "t2i-adapter_diffusers_xl_openpose.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/t2i-adapter_xl_canny.safetensors?download=true",
    filename: "t2i-adapter_xl_canny.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/t2i-adapter_diffusers_xl_sketch.safetensors?download=true",
    filename: "t2i-adapter_diffusers_xl_sketch.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/t2i-adapter_xl_sketch.safetensors?download=true",
    filename: "t2i-adapter_xl_sketch.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/thibaud_xl_openpose.safetensors?download=true",
    filename: "thibaud_xl_openpose.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/thibaud_xl_openpose_256lora.safetensors?download=true",
    filename: "thibaud_xl_openpose_256lora.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/spaces/LiheYoung/Depth-Anything/resolve/main/checkpoints/depth_anything_vitl14.pth?download=true",
    filename: "depth_anything_vitl14.pth",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/spaces/LiheYoung/Depth-Anything/resolve/main/checkpoints/depth_anything_vitb14.pth?download=true",
    filename: "depth_anything_vitb14.pth",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/huchenlei/animal_openpose/resolve/main/control_sd15_animal_openpose.pth?download=true",
    filename: "control_sd15_animal_openpose.pth",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/hr16/ControlNet-HandRefiner-pruned/resolve/main/control_sd15_inpaint_depth_hand_fp16.safetensors?download=true",
    filename: "control_sd15_inpaint_depth_hand_fp16.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/SargeZT/controlnet-sd-xl-1.0-softedge-dexined/resolve/main/controlnet-sd-xl-1.0-softedge-dexined.safetensors?download=true",
    filename: "controlnet-sd-xl-1.0-softedge-dexined.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/InstantX/InstantID/resolve/main/ControlNetModel/diffusion_pytorch_model.safetensors?download=true",
    filename: "instantid-controlnet.safetensors",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/Annotators/resolve/main/res101.pth",
    filename: "res101.pth",
    path: "controlnet",
  },
  {
    url: "https://huggingface.co/lllyasviel/Annotators/resolve/main/latest_net_G.pth?download=true",
    filename: "latest_net_G.pth",
    path: "controlnet",
  },
];

const OTHERMODELS = [
  {
    url: "https://huggingface.co/lllyasviel/Annotators/resolve/main/ControlNetHED.pth",
    filename: "ControlNetHED.pth",
    path: "annotators",
  },
  {
    url: "https://huggingface.co/lllyasviel/Annotators/resolve/main/res101.pth",
    filename: "res101.pth",
    path: "annotators",
  },
  {
    url: "https://huggingface.co/guoyww/animatediff/resolve/cd71ae134a27ec6008b968d6419952b0c0494cf2/mm_sd_v14.ckpt?download=true",
    filename: "mm_sd_v14.ckpt",
    path: "animatediff_models",
  },
  {
    url: "https://huggingface.co/guoyww/animatediff/resolve/cd71ae134a27ec6008b968d6419952b0c0494cf2/mm_sd_v15.ckpt?download=true",
    filename: "mm_sd_v15.ckpt",
    path: "animatediff_models",
  },
  {
    url: "https://huggingface.co/guoyww/animatediff/resolve/cd71ae134a27ec6008b968d6419952b0c0494cf2/mm_sd_v15_v2.ckpt?download=true",
    filename: "mm_sd_v15_v2.ckpt",
    path: "animatediff_models",
  },
  {
    url: "https://huggingface.co/guoyww/animatediff/resolve/cd71ae134a27ec6008b968d6419952b0c0494cf2/v3_sd15_mm.ckpt?download=true",
    filename: "v3_sd15_mm.ckpt",
    path: "animatediff_models",
  },
  {
    url: "https://huggingface.co/manshoety/AD_Stabilized_Motion/resolve/main/mm-Stabilized_high.pth?download=true",
    filename: "mm-Stabilized_high.pth",
    path: "animatediff_models",
  },
  {
    url: "https://huggingface.co/manshoety/AD_Stabilized_Motion/resolve/main/mm-Stabilized_mid.pth?download=true",
    filename: "mm-Stabilized_mid.pth",
    path: "animatediff_models",
  },
  {
    url: "https://huggingface.co/manshoety/beta_testing_models/resolve/main/mm-p_0.5.pth?download=true",
    filename: "mm-p_0.5.pth",
    path: "animatediff_models",
  },
  {
    url: "https://huggingface.co/manshoety/beta_testing_models/resolve/main/mm-p_0.75.pth?download=true",
    filename: "mm-p_0.75.pth",
    path: "animatediff_models",
  },
  {
    url: "https://huggingface.co/CiaraRowles/TemporalDiff/resolve/main/temporaldiff-v1-animatediff.safetensors?download=true",
    filename: "temporaldiff-v1-animatediff.safetensors",
    path: "animatediff_models",
  },
  {
    url: "https://huggingface.co/guoyww/animatediff/resolve/main/v2_lora_PanLeft.ckpt?download=true",
    filename: "v2_lora_PanLeft.ckpt",
    path: "animatediff_motion_lora",
  },
  {
    url: "https://huggingface.co/guoyww/animatediff/resolve/main/v2_lora_PanRight.ckpt?download=true",
    filename: "v2_lora_PanRight.ckpt",
    path: "animatediff_motion_lora",
  },
  {
    url: "https://huggingface.co/guoyww/animatediff/resolve/main/v2_lora_RollingAnticlockwise.ckpt?download=true",
    filename: "v2_lora_RollingAnticlockwise.ckpt",
    path: "animatediff_motion_lora",
  },
  {
    url: "https://huggingface.co/guoyww/animatediff/resolve/main/v2_lora_RollingClockwise.ckpt?download=true",
    filename: "v2_lora_RollingClockwise.ckpt",
    path: "animatediff_motion_lora",
  },
  {
    url: "https://huggingface.co/guoyww/animatediff/resolve/main/v2_lora_TiltDown.ckpt?download=true",
    filename: "v2_lora_TiltDown.ckpt",
    path: "animatediff_motion_lora",
  },
  {
    url: "https://huggingface.co/guoyww/animatediff/resolve/main/v2_lora_TiltUp.ckpt?download=true",
    filename: "v2_lora_TiltUp.ckpt",
    path: "animatediff_motion_lora",
  },
  {
    url: "https://huggingface.co/guoyww/animatediff/resolve/main/v2_lora_ZoomIn.ckpt?download=true",
    filename: "v2_lora_ZoomIn.ckpt",
    path: "animatediff_motion_lora",
  },
  {
    url: "https://huggingface.co/guoyww/animatediff/resolve/main/v2_lora_ZoomOut.ckpt?download=true",
    filename: "v2_lora_ZoomOut.ckpt",
    path: "animatediff_motion_lora",
  },
  {
    url: "https://huggingface.co/ViperYX/BiRefNet/resolve/main/BiRefNet-DIS_ep580.pth?download=true",
    filename: "BiRefNet-DIS_ep580.pth",
    path: "BiRefNet",
  },
  {
    url: "https://huggingface.co/ViperYX/BiRefNet/resolve/main/BiRefNet-ep480.pth?download=true",
    filename: "BiRefNet-ep480.pth",
    path: "BiRefNet",
  },
  {
    url: "https://huggingface.co/ViperYX/BiRefNet/resolve/main/pvt_v2_b2.pth?download=true",
    filename: "pvt_v2_b2.pth",
    path: "BiRefNet",
  },
  {
    url: "https://huggingface.co/ViperYX/BiRefNet/resolve/main/pvt_v2_b5.pth?download=true",
    filename: "pvt_v2_b5.pth",
    path: "BiRefNet",
  },
  {
    url: "https://huggingface.co/ViperYX/BiRefNet/resolve/main/swin_base_patch4_window12_384_22kto1k.pth?download=true",
    filename: "swin_base_patch4_window12_384_22kto1k.pth",
    path: "BiRefNet",
  },
  {
    url: "https://huggingface.co/ViperYX/BiRefNet/resolve/main/swin_large_patch4_window12_384_22kto1k.pth?download=true",
    filename: "swin_large_patch4_window12_384_22kto1k.pth",
    path: "BiRefNet",
  },
  {
    url: "https://huggingface.co/h94/IP-Adapter/resolve/main/models/image_encoder/model.safetensors",
    filename: "CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors",
    path: "clip_vision",
  },
  {
    url: "https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/image_encoder/model.safetensors",
    filename: "CLIP-ViT-bigG-14-laion2B-39B-b160k.safetensors",
    path: "clip_vision",
  },
  {
    url: "https://huggingface.co/openai/clip-vit-large-patch14/resolve/main/model.safetensors?download=true",
    filename: "clip-vit-large-patch14.safetensors",
    path: "clip_vision",
  },
  {
    url: "https://huggingface.co/Salesforce/blip-image-captioning-base/resolve/main/config.json?download=true",
    filename: "config.json",
    path: "clip_interrogator/Salesforce/blip-image-captioning-base",
  },
  {
    url: "https://huggingface.co/Salesforce/blip-image-captioning-base/resolve/main/preprocessor_config.json?download=true",
    filename: "preprocessor_config.json",
    path: "clip_interrogator/Salesforce/blip-image-captioning-base",
  },
  {
    url: "https://huggingface.co/Salesforce/blip-image-captioning-base/resolve/main/pytorch_model.bin?download=true",
    filename: "pytorch_model.bin",
    path: "clip_interrogator/Salesforce/blip-image-captioning-base",
  },
  {
    url: "https://huggingface.co/Salesforce/blip-image-captioning-base/resolve/main/special_tokens_map.json?download=true",
    filename: "special_tokens_map.json",
    path: "clip_interrogator/Salesforce/blip-image-captioning-base",
  },
  {
    url: "https://huggingface.co/Salesforce/blip-image-captioning-base/resolve/main/tokenizer.json?download=true",
    filename: "tokenizer.json",
    path: "clip_interrogator/Salesforce/blip-image-captioning-base",
  },
  {
    url: "https://huggingface.co/Salesforce/blip-image-captioning-base/resolve/main/tokenizer_config.json?download=true",
    filename: "tokenizer_config.json",
    path: "clip_interrogator/Salesforce/blip-image-captioning-base",
  },
  {
    url: "https://huggingface.co/Salesforce/blip-image-captioning-base/resolve/main/vocab.txt?download=true",
    filename: "vocab.txt",
    path: "clip_interrogator/Salesforce/blip-image-captioning-base",
  },
  {
    url: "https://civitai.com/api/download/models/77169?type=Model&format=PickleTensor",
    filename: "badDream.pt",
    path: "embeddings",
  },
  {
    url: "https://civitai.com/api/download/models/77173?type=Model&format=PickleTensor",
    filename: "unrealisticDream.pt",
    path: "embeddings",
  },
  {
    url: "https://civitai.com/api/download/models/94057?type=Model&format=PickleTensor",
    filename: "fastNegativeV2.pt",
    path: "embeddings",
  },
  {
    url: "https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid_sd15.bin",
    filename: "ip-adapter-faceid_sd15.bin",
    path: "ipadapter",
  },
  {
    url: "https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid-plusv2_sd15.bin",
    filename: "ip-adapter-faceid-plusv2_sd15.bin",
    path: "ipadapter",
  },
  {
    url: "https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid-portrait-v11_sd15.bin",
    filename: "ip-adapter-faceid-portrait-v11_sd15.bin",
    path: "ipadapter",
  },
  {
    url: "https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid_sdxl.bin",
    filename: "ip-adapter-faceid_sdxl.bin",
    path: "ipadapter",
  },
  {
    url: "https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid-plusv2_sdxl.bin",
    filename: "ip-adapter-faceid-plusv2_sdxl.bin",
    path: "ipadapter",
  },
  {
    url: "https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid-portrait_sdxl.bin",
    filename: "ip-adapter-faceid-portrait_sdxl.bin",
    path: "ipadapter",
  },
  {
    url: "https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid-portrait_sdxl_unnorm.bin?download=true",
    filename: "ip-adapter-faceid-portrait_sdxl_unnorm.bin",
    path: "ipadapter",
  },
  {
    url: "https://huggingface.co/h94/IP-Adapter/resolve/main/models/ip-adapter_sd15.safetensors",
    filename: "ip-adapter_sd15.safetensors",
    path: "ipadapter",
  },
  {
    url: "https://huggingface.co/h94/IP-Adapter/resolve/main/models/ip-adapter_sd15_light_v11.bin",
    filename: "ip-adapter_sd15_light_v11.bin",
    path: "ipadapter",
  },
  {
    url: "https://huggingface.co/h94/IP-Adapter/resolve/main/models/ip-adapter-plus_sd15.safetensors",
    filename: "ip-adapter-plus_sd15.safetensors",
    path: "ipadapter",
  },
  {
    url: "https://huggingface.co/h94/IP-Adapter/resolve/main/models/ip-adapter-plus-face_sd15.safetensors",
    filename: "ip-adapter-plus-face_sd15.safetensors",
    path: "ipadapter",
  },
  {
    url: "https://huggingface.co/h94/IP-Adapter/resolve/main/models/ip-adapter-full-face_sd15.safetensors",
    filename: "ip-adapter-full-face_sd15.safetensors",
    path: "ipadapter",
  },
  {
    url: "https://huggingface.co/h94/IP-Adapter/resolve/main/models/ip-adapter_sd15_vit-G.safetensors",
    filename: "ip-adapter_sd15_vit-G.safetensors",
    path: "ipadapter",
  },
  {
    url: "https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/ip-adapter_sdxl_vit-h.safetensors",
    filename: "ip-adapter_sdxl_vit-h.safetensors",
    path: "ipadapter",
  },
  {
    url: "https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/ip-adapter-plus_sdxl_vit-h.safetensors",
    filename: "ip-adapter-plus_sdxl_vit-h.safetensors",
    path: "ipadapter",
  },
  {
    url: "https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/ip-adapter-plus-face_sdxl_vit-h.safetensors",
    filename: "ip-adapter-plus-face_sdxl_vit-h.safetensors",
    path: "ipadapter",
  },
  {
    url: "https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/ip-adapter_sdxl.safetensors",
    filename: "ip-adapter_sdxl.safetensors",
    path: "ipadapter",
  },
  {
    url: "https://huggingface.co/InstantX/InstantID/resolve/main/ip-adapter.bin?download=true",
    filename: "instantid-ip-adapter.bin",
    path: "instantid",
  },
  {
    url: "https://huggingface.co/MonsterMMORPG/tools/resolve/main/1k3d68.onnx?download=true",
    filename: "1k3d68.onnx",
    path: "insightface/models/antelopev2",
  },
  {
    url: "https://huggingface.co/MonsterMMORPG/tools/resolve/main/2d106det.onnx?download=true",
    filename: "2d106det.onnx",
    path: "insightface/models/antelopev2",
  },
  {
    url: "https://huggingface.co/MonsterMMORPG/tools/resolve/main/genderage.onnx?download=true",
    filename: "genderage.onnx",
    path: "insightface/models/antelopev2",
  },
  {
    url: "https://huggingface.co/MonsterMMORPG/tools/resolve/main/glintr100.onnx?download=true",
    filename: "glintr100.onnx",
    path: "insightface/models/antelopev2",
  },
  {
    url: "https://huggingface.co/MonsterMMORPG/tools/resolve/main/scrfd_10g_bnkps.onnx?download=true",
    filename: "scrfd_10g_bnkps.onnx",
    path: "insightface/models/antelopev2",
  },
  {
    url: "https://huggingface.co/DavidHoa/buffalo_l/resolve/main/1k3d68.onnx?download=true",
    filename: "1k3d68.onnx",
    path: "insightface/models/buffalo_l",
  },
  {
    url: "https://huggingface.co/DavidHoa/buffalo_l/resolve/main/2d106det.onnx?download=true",
    filename: "2d106det.onnx",
    path: "insightface/models/buffalo_l",
  },
  {
    url: "https://huggingface.co/DavidHoa/buffalo_l/resolve/main/det_10g.onnx?download=true",
    filename: "det_10g.onnx",
    path: "insightface/models/buffalo_l",
  },
  {
    url: "https://huggingface.co/DavidHoa/buffalo_l/resolve/main/genderage.onnx?download=true",
    filename: "genderage.onnx",
    path: "insightface/models/buffalo_l",
  },
  {
    url: "https://huggingface.co/DavidHoa/buffalo_l/resolve/main/w600k_r50.onnx?download=true",
    filename: "w600k_r50.onnx",
    path: "insightface/models/buffalo_l",
  },
  {
    url: "https://huggingface.co/ShilongLiu/GroundingDINO/resolve/main/groundingdino_swint_ogc.pth",
    filename: "groundingdino_swint_ogc.pth",
    path: "grounding-dino",
  },
  {
    url: "https://huggingface.co/ShilongLiu/GroundingDINO/resolve/main/groundingdino_swinb_cogcoor.pth",
    filename: "groundingdino_swinb_cogcoor.pth",
    path: "grounding-dino",
  },
  {
    url: "https://huggingface.co/ShilongLiu/GroundingDINO/resolve/main/GroundingDINO_SwinT_OGC.cfg.py",
    filename: "GroundingDINO_SwinT_OGC.cfg.py",
    path: "grounding-dino",
  },
  {
    url: "https://huggingface.co/ShilongLiu/GroundingDINO/resolve/main/GroundingDINO_SwinB.cfg.py",
    filename: "GroundingDINO_SwinB.cfg.py",
    path: "grounding-dino",
  },
  {
    url: "https://huggingface.co/briaai/RMBG-1.4/resolve/main/model.pth?download=true",
    filename: "RMBG-1.4.pth",
    path: "rembg",
  },
  {
    url: "https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth",
    filename: "sam_vit_h_4b8939.pth",
    path: "sams",
  },
  {
    url: "https://dl.fbaipublicfiles.com/segment_anything/sam_vit_l_0b3195.pth",
    filename: "sam_vit_l_0b3195.pth",
    path: "sams",
  },
  {
    url: "https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth",
    filename: "sam_vit_b_01ec64.pth",
    path: "sams",
  },
  {
    url: "https://huggingface.co/lkeab/hq-sam/resolve/main/sam_hq_vit_h.pth",
    filename: "sam_hq_vit_h.pth",
    path: "sams",
  },
  {
    url: "https://huggingface.co/lkeab/hq-sam/resolve/main/sam_hq_vit_l.pth",
    filename: "sam_hq_vit_l.pth",
    path: "sams",
  },
  {
    url: "https://huggingface.co/lkeab/hq-sam/resolve/main/sam_hq_vit_b.pth",
    filename: "sam_hq_vit_b.pth",
    path: "sams",
  },
  {
    url: "https://huggingface.co/TencentARC/T2I-Adapter/resolve/main/models/coadapter-style-sd15v1.pth?download=true",
    filename: "coadapter-style-sd15v1.pth",
    path: "style_models",
  },
  {
    url: "https://huggingface.co/google-bert/bert-base-uncased/resolve/main/config.json?download=true",
    filename: "config.json",
    path: "bert-base-uncased",
  },
  {
    url: "https://huggingface.co/google-bert/bert-base-uncased/resolve/main/model.safetensors?download=true",
    filename: "model.safetensors",
    path: "bert-base-uncased",
  },
  {
    url: "https://huggingface.co/google-bert/bert-base-uncased/resolve/main/tokenizer.json?download=true",
    filename: "tokenizer.json",
    path: "bert-base-uncased",
  },
  {
    url: "https://huggingface.co/google-bert/bert-base-uncased/resolve/main/tokenizer_config.json?download=true",
    filename: "tokenizer_config.json",
    path: "bert-base-uncased",
  },
  {
    url: "https://huggingface.co/google-bert/bert-base-uncased/resolve/main/vocab.txt?download=true",
    filename: "vocab.txt",
    path: "bert-base-uncased",
  },
  {
    url: "https://huggingface.co/huchenlei/IC-Light-ldm/resolve/main/iclight_sd15_fbc_unet_ldm.safetensors?download=true",
    filename: "iclight_sd15_fbc_unet_ldm.safetensors",
    path: "unet",
  },
  {
    url: "https://huggingface.co/huchenlei/IC-Light-ldm/resolve/main/iclight_sd15_fc_unet_ldm.safetensors?download=true",
    filename: "iclight_sd15_fc_unet_ldm.safetensors",
    path: "unet",
  },
  {
    url: "https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.1/RealESRGAN_x2plus.pth",
    filename: "RealESRGAN_x2plus.pth",
    path: "upscale_models",
  },
  {
    url: "https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth",
    filename: "RealESRGAN_x4plus.pth",
    path: "upscale_models",
  },
  {
    url: "https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.2.4/RealESRGAN_x4plus_anime_6B.pth",
    filename: "RealESRGAN_x4plus_anime_6B.pth",
    path: "upscale_models",
  },
  {
    url: "https://objectstorage.us-phoenix-1.oraclecloud.com/n/ax6ygfvpvzka/b/open-modeldb-files/o/1x-ITF-SkinDiffDetail-Lite-v1.pth",
    filename: "1x-ITF-SkinDiffDetail-Lite-v1.pth",
    path: "upscale_models",
  },
  {
    url: "https://huggingface.co/FacehugmanIII/4x_foolhardy_Remacri/resolve/main/4x_foolhardy_Remacri.pth?download=true",
    filename: "4x_foolhardy_Remacri.pth",
    path: "upscale_models",
  },
  {
    url: "https://civitai.com/api/download/models/164891?type=Model&format=PickleTensor",
    filename: "4x-UltraMix_Balanced.pt",
    path: "upscale_models",
  },
  {
    url: "https://civitai.com/api/download/models/164888?type=Model&format=PickleTensor",
    filename: "4x-UltraMix_Restore.pt",
    path: "upscale_models",
  },
  {
    url: "https://civitai.com/api/download/models/164882?type=Model&format=PickleTensor",
    filename: "4x-UltraMix_Smooth.pt",
    path: "upscale_models",
  },
  {
    url: "https://civitai.com/api/download/models/125843?type=Model&format=PickleTensor",
    filename: "4x-UltraSharp.pt",
    path: "upscale_models",
  },
  {
    url: "https://civitai.com/api/download/models/328284",
    filename: "8x_NMKD-Superscale_150000_G.pth",
    path: "upscale_models",
  },
  {
    url: "https://huggingface.co/uwg/upscaler/resolve/main/ESRGAN/4x_NMKD-Siax_200k.pth",
    filename: "4x_NMKD-Siax_200k.pth",
    path: "upscale_models",
  },
  {
    url: "https://huggingface.co/uwg/upscaler/resolve/main/ESRGAN/4x_Nickelback_70000G.pth",
    filename: "4x_Nickelback_70000G.pth",
    path: "upscale_models",
  },
  {
    url: "https://huggingface.co/kadirnar/BSRGANx2/resolve/main/BSRGANx2.pth?download=true",
    filename: "BSRGANx2.pth",
    path: "upscale_models",
  },
  {
    url: "https://civitai.com/api/download/models/311162?type=Model&format=SafeTensor",
    filename: "vae-ft-mse-840000-ema-pruned.safetensors",
    path: "vae",
  },
  {
    url: "https://huggingface.co/WarriorMama777/OrangeMixs/resolve/main/VAEs/orangemix.vae.pt?download=true",
    filename: "orangemix.vae.pt",
    path: "vae",
  },
  {
    url: "https://civitai.com/api/download/models/333245?type=Model&format=SafeTensor",
    filename: "sdxl_vae.safetensors",
    path: "vae",
  },
  {
    url: "https://github.com/enesmsahin/simple-lama-inpainting/releases/download/v0.1.0/big-lama.pt",
    filename: "big-lama.pt",
    path: "lama",
  },
  {
    url: "https://huggingface.co/succinctly/text2image-prompt-generator/resolve/main/config.json?download=true",
    filename: "config.json",
    path: "prompt_generator/text2image-prompt-generator",
  },
  {
    url: "https://huggingface.co/succinctly/text2image-prompt-generator/resolve/main/merges.txt?download=true",
    filename: "merges.txt",
    path: "prompt_generator/text2image-prompt-generator",
  },
  {
    url: "https://huggingface.co/succinctly/text2image-prompt-generator/resolve/main/pytorch_model.bin?download=true",
    filename: "pytorch_model.bin",
    path: "prompt_generator/text2image-prompt-generator",
  },
  {
    url: "https://huggingface.co/succinctly/text2image-prompt-generator/resolve/main/special_tokens_map.json?download=true",
    filename: "special_tokens_map.json",
    path: "prompt_generator/text2image-prompt-generator",
  },
  {
    url: "https://huggingface.co/succinctly/text2image-prompt-generator/resolve/main/tokenizer.json?download=true",
    filename: "tokenizer.json",
    path: "prompt_generator/text2image-prompt-generator",
  },
  {
    url: "https://huggingface.co/succinctly/text2image-prompt-generator/resolve/main/tokenizer_config.json?download=true",
    filename: "tokenizer_config.json",
    path: "prompt_generator/text2image-prompt-generator",
  },
  {
    url: "https://huggingface.co/succinctly/text2image-prompt-generator/resolve/main/training_args.bin?download=true",
    filename: "training_args.bin",
    path: "prompt_generator/text2image-prompt-generator",
  },
  {
    url: "https://huggingface.co/succinctly/text2image-prompt-generator/resolve/main/vocab.json?download=true",
    filename: "vocab.json",
    path: "prompt_generator/text2image-prompt-generator",
  },
  {
    url: "https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/resolve/main/config.json?download=true",
    filename: "config.json",
    path: "prompt_generator/opus-mt-zh-en",
  },
  {
    url: "https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/resolve/main/generation_config.json?download=true",
    filename: "generation_config.json",
    path: "prompt_generator/opus-mt-zh-en",
  },
  {
    url: "https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/resolve/main/metadata.json?download=true",
    filename: "metadata.json",
    path: "prompt_generator/opus-mt-zh-en",
  },
  {
    url: "https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/resolve/main/pytorch_model.bin?download=true",
    filename: "pytorch_model.bin",
    path: "prompt_generator/opus-mt-zh-en",
  },
  {
    url: "https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/resolve/main/source.spm?download=true",
    filename: "source.spm",
    path: "prompt_generator/opus-mt-zh-en",
  },
  {
    url: "https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/resolve/main/tokenizer_config.json?download=true",
    filename: "tokenizer_config.json",
    path: "prompt_generator/opus-mt-zh-en",
  },
  {
    url: "https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/resolve/main/target.spm?download=true",
    filename: "target.spm",
    path: "prompt_generator/opus-mt-zh-en",
  },
  {
    url: "https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/resolve/main/vocab.json?download=true",
    filename: "vocab.json",
    path: "prompt_generator/opus-mt-zh-en",
  },
];

export const ALL_MODELS: MarketModel[] = [
  ...CHECKPOINTS,
  ...LORAS,
  ...CONTROLNETS,
  ...OTHERMODELS
].map((model) => {
  const data = model as any;
  const item: MarketModel = {
    ...model,
    reference: data.reference,
    name: model.filename,
    type: ModelType.Other,
    base_model: data.baseModel,
    sha256: data.sha256,
    download_url: model.url,
    save_path: model.path,
    description: data.description,
    source: "other",
    meta: {
      image_url: data.image_url ?? data.imageUrls ? data.imageUrls[0] : "",
      image_urls: data.imageUrls as string[]
    }
  }

  if (model.url.includes("huggingface.co")) {
    item.source = "huggingface"
  }

  if (model.url.includes("civitai.com")) {
    item.source = "civitai"
  }

  switch (model.path) {
    case "checkpoints":
      item.type = ModelType.Checkpoint;
      break;
    case "loras":
      item.type = ModelType.LoRA;
      break;
    case "controlnet":
      item.type = ModelType.Controlnet;
      break;
  }

  item.id = item.type + "-" + item.name;
  
  return item
})

export const LORA_MODELS = ALL_MODELS.filter((model) => model.type === ModelType.LoRA);
export const CONTROLNET_MODELS = ALL_MODELS.filter((model) => model.type === ModelType.Controlnet);
export const CHECKPOINT_MODELS = ALL_MODELS.filter((model) => model.type === ModelType.Checkpoint);

export const MODELS_MAP: Record<string, MarketModel> = ALL_MODELS.reduce((acc, model) => {
  acc[model.filename] = model;
  return acc;
}, {} as any);


