name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish webextension
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2.2.4
      with:
        version: 7.14.2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: pnpm install --frozen-lockfile
    - name: Build
      run: |
        cd apps/ai-reply-assitant
        pnpm build
    - name: Zip
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r ai-reply.zip chrome-mv3-prod
        working-directory: apps/ai-reply-assitant/build
    - name: Upload & release
      uses: mnao305/chrome-extension-upload@v4.0.1
      with:
        file-path: apps/ai-reply-assistant/build/ai-reply.zip
        extension-id: hogefuga(extension id)
        client-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        refresh-token: ${{ secrets.REFRESH_TOKEN }}
