name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install pnpm
      run: |
        npm i -g pnpm

    - name: Install Dependencies
      run: |
        pnpm i 
        npm run install-package-builder

    - name: Build and Release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NODE_ENV: production
      run: |
        cd ./apps/electron-package
        npm run compile
        npm run make